### ISSUE TITLE
Azure permissions

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-dotnet#24]
Unable to notify of an exception on azure ->

Exception=System.TypeInitializationException: The type initializer for 'Bugsnag.Diagnostics' threw an exception. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at System.Management.ManagementScope.InitializeGuts(Object o)
at System.Management.ManagementScope.Initialize()
at System.Management.ManagementObjectSearcher.Initialize()
at System.Management.ManagementObjectSearcher.Get()
at Bugsnag.Diagnostics.IsServerVersion()
at Bugsnag.Diagnostics.GetWin32NTVersion()
at Bugsnag.Diagnostics.GetOSInfo()
at Bugsnag.Diagnostics..cctor()

**Comment by CodeHex** [comment]
It may be the WMI query used to determine if the OS is the server version. 

https://github.com/bugsnag/bugsnag-dotnet/blob/master/src/Bugsnag.Core/Diagnostics.cs#L134

Looks like you have to be Administrator to execute the query, hence accessed denied exception. Could wrap it in a try catch and return something like e.g. "Windows 8 / Windows Server 2012" if you don't have the relevant permissions. Haven't found a way to determine the difference without WMI yet...but I'll keep looking.

**Comment by snmaynard** [comment]
I think your suggestion of returning both in the case where theres an exception seems totally sensible!
