### ISSUE TITLE
Double exceptions from child actions in ASP.NET MVC

### ISSUE THREAD

**Issue by tkirill** [bugsnag/bugsnag-dotnet#43]
# Description

In #42 the call of `base.OnException` was removed.  It causes double reporting exceptions from child actions: 

* First from child action itself
* Second from parent action

# Steps to reproduce

I created minimal MVC 5 project to demonstrate and reproduce the problem: [tkirill/bugsnag-double-exception](https://github.com/tkirill/bugsnag-double-exception).

1. Build the project.
2. Go to "/".
3. Yellow error page will be displayed.
4. Open "C:\logs\double-exception.log".

In the log file will be two exceptions but should be only one -- the last.

    =============
    
    System.NotImplementedException: The method or operation is not implemented.
       at DoubleException.HomeController.Exception() in C:\Users\t_kirill\workplace\bugsnag\double-exception\reproduce\DoubleException\DoubleException\HomeController.cs:line 17
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
    
    =============
    
    System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.NotImplementedException: The method or operation is not implemented.
       at DoubleException.HomeController.Exception() in C:\Users\t_kirill\workplace\bugsnag\double-exception\reproduce\DoubleException\DoubleException\HomeController.cs:line 17
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
       at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
       at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
       at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.<>c__DisplayClass4.<Wrap>b__3()
       at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func)
       at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)
       at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)
       at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage)
       at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm)
       at System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter)
       at System.Web.Mvc.Html.ChildActionExtensions.Action(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues)
       at ASP._Page_Views_Home_Index_cshtml.Execute() in c:\Users\t_kirill\workplace\bugsnag\double-exception\reproduce\doubleexception\doubleexception\Views\Home\Index.cshtml:line 13
       at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
       at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
       at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
       at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

# Why

`HandleErrorAttribute.OnException` [contains](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L63) corresponding `if`.  I think this `if` should be in `BugsnagExceptionHandler` too.  I checked this [here](https://github.com/tkirill/bugsnag-double-exception/blob/master/DoubleException/DoubleException/SampleExceptionFilter.cs#L15).

There are other helpful `if`s in `HandleErrorAttribute.OnException`: [one](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L70), [two](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L79).

I believe the good solution will be to inherit `BugsnagExceptionHandler` from `FilterAttribute, IExceptionFilter` and copy `HandleErrorAttribute.OnException` without rendering error view.

**Comment by CodeHex** [comment]
I don't think this is happening because of the removal of the `base.OnException` call. I took your sample project, added a call to `base.OnException()` and the exception is still reported twice. I think this will always happen if any exception occurs in a child action.

I've also checked with the Bugsnag library and in both versions there are two events (aggregated as the same error)

Although the `base.OnException()` will do nothing for child actions, the Bugsnag notification code will still be executed regardless. This will send two exception reports, one exception for the child action and one nested exception for the parent action saying it can't execute the child action.

I think this is a separate issue about when exceptions are reported i.e. should we rely on parent actions to report child action exceptions or send two. Bugsnag will identify them as the same error as the underlying root exception is the same.

For the default `HandleErrorAttribute` its only renders the error page if (corresponding to your `if`s..)
* Its not a child action [[here](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L63)]
* If something else has already handled the exception i.e. set `filterContext.ExceptionHandled` to `true` [[here](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L70)]
* If custom errors is not enabled since the default ASP.NET handler will render the error page [[here](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L70)]
* Only if its a server error (500) as it doesn't want to handle throwing a HTTPExceptions of other status codes [[here](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L79)]
* If this attribute has been set up to only handle this type of error i.e. `ExceptionType` has been specifically set. Will not return it not set. [[here](https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/HandleErrorAttribute.cs#L84)]

I think although these are the right things to do for showing an error page we may not want the Bugsnag attribute to do the same. The attribute will try to report as much as possible and is therefore currently set to
* Reporting on exception in child action exceptions **and** when it parent action has called it
* Regardless of whether the exception was handled (and we will not mark it as handled)
* Regardless of whether custom error views are enabled
* Report on any thrown HTTPExceptions, not just 500's
* Doesn't care about specific Exception types, just reports on them all

It may be that we need to make a more advanced attribute which lets you control when exceptions are notified or change this default behaviour.

**Comment by tkirill** [comment]
> I took your sample project, added a call to base.OnException() and the exception is still reported twice.

Yeah, my bad.  You're right and if your system groups exceptions then there is no real issue except possibly redundant API calls.  Thanks for explanation!

**Comment by CodeHex** [comment]
I think currently the Bugsnag attribute is reporting as much as it can, which we want be default.
